import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NavMenu from "./components/nav-menu";
import logoSrc from "../../../public/logoSG.svg";
import Footer from "./components/footer";
import { fetchSettings } from "@/api/sanityApi";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const settingsData = await fetchSettings();
  console.log(settingsData);

  const testSettings = {
    navSettings: {
      logoSrc: logoSrc,
      logoAlt: "test",
      button: "primary",
    },
    footerSettings: {
      banner: true,
      heading: "Wil je ons ook helpen?",
      paragraph: "Jouw donatie stelt ons in staat om verse ingrediënten te verkrijgen, onze keuken draaiende te houden en de maaltijden aan te bieden aan mensen die het minder breed hebben.",
      buttonGroup: {
          buttonLink: "/haihai",
          buttonText: "Doneer nu",
          buttonVariant: "secondary" ,
      }
    },
    contactInfo: {
      companyName: "Contact us",
      companyStreet: "123 test street",
      companyPostal: "12345 Leiden",
      companyPhone: "123456789",
      companyEmail: "test@email.nl",
      companyInstagram: "https://www.instagram.com/",
      companyFacebook: "https://www.facebook.com/",
      companyLinkedIn: "https://www.linkedin.com/",
      copyright: "© 2021",
    },
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <NavMenu settings={testSettings} menuAr={menuData.menu} /> */}
        {children}
        {/* <Footer settings={testSettings} menuAr={menuData.menu} /> */}
      </body>
    </html>
  );
}
