import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NavMenu from "./components/nav-menu";
import Footer from "./components/footer";
import { fetchSettings, formatSettingsData } from "@/api/sanityApi";
import { Capriola } from "next/font/google";
import localFont from "@next/font/local";
import { useParams } from "next/navigation";

const capriola = Capriola({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-capriola",
});
// const manrope = Manrope({
//   subsets: ["latin"],
//   weight: "400",
//   variable: "--font-manrope",
// });
const lambda = localFont({
  src: "../../../fonts/Lambda-Regular.ttf",
  weight: "400",
  variable: "--font-lambda",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await fetchSettings();
  const settingsData = formatSettingsData(data);

  return (
    <html lang="en" className={`${capriola.variable} ${lambda.variable}`}>
      <body className={inter.className}>
        <NavMenu
          settings={settingsData.navSettings}
          menuAr={settingsData.menu}
        />
        {children}
        <Footer
          settings={settingsData.footerSettings}
          contactInfo={settingsData.contactInfo}
          logo={settingsData.navSettings}
          menuAr={settingsData.menu}
        />
      </body>
    </html>
  );
}
