import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NavMenu from "./components/nav-menu";
import logoSrc from "../../public/logoSG.svg";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const testAr = [
    { url: "test-one", label: "test one", _key: "1" },
    { url: "test-two", label: "test two", _key: "2" },
    { url: "test-three", label: "test three", _key: "3" },
  ];
  const testSettings = {
    navSettings: {
      logoSrc: logoSrc,
      logoAlt: "test",
      button: "primary",
    },
    footerSettings: {
      banner: true,
      heading: "Test heading",
      paragraph: "lorem ipsum dolor sit amet",
    },
    contactInfo: {
      companyName: "Contact us",
      companyStreet: "123 test street",
      companyPostal: "12345 Leiden",
      companyPhone: "123456789",
      companyEmail: "test@email.nl",
      companyInstagram: "https://www.instagram.com/",
      companyFacebook: "https://www.facebook.com/",
      companyLinkedIn: "https://www.linkedin.com/",
      copyRight: "© 2021",
    },
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavMenu settings={testSettings} menuAr={testAr} />
        {children}
        <Footer settings={testSettings} menuAr={testAr} />
      </body>
    </html>
  );
}
